# Generated by Django 5.2.7 on 2026-02-02 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Done', 'Done')], default='To do', max_length=20)),
                ('assigned_by', models.ForeignKey(db_column='id_assigned_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Done', 'Done')], default='To do', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(db_column='id_task', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='api_app.task')),
            ],
            options={
                'db_table': 'subtasks',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Assigned', 'Assigned'), ('Viewer', 'Viewer')], default='Assigned', max_length=10)),
                ('task', models.ForeignKey(db_column='id_task', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api_app.task')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='task_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tasks',
                'constraints': [models.UniqueConstraint(fields=('task', 'user'), name='task_user_unique')],
            },
        ),
    ]
